#!/bin/bash
#
 REPO="/git/www/github-pages"
BUILD="$REPO/build"
 DOCS="docs/fltk-1.4"
#
echo ""
echo "Updating fltk repository $BUILD"
echo ""
#
cd $BUILD
git pull
#
echo ""
echo "Building docs ..."
echo ""
#
make clean
cd documentation
pwd
make
make html
make pdf
#
echo ""
echo "Moving docs to their destination ..."
echo ""
#
cd $REPO
git rm $DOCS/*
rm -rf $DOCS/
mv $BUILD/documentation/html $DOCS
mv $BUILD/documentation/fltk.pdf $DOCS/
#
echo ""
echo "Build done."
echo ""
date
echo ""
echo "Committing and pushing ..."
echo ""
git add $DOCS/
git commit -m "Update documentation"
#
# git push
#
echo ""
echo "Done."
echo ""
